import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import Providers from "./Providers";
import { Navbar } from "../components/common/Navbar";
import { Footer } from "../components/common/Footer";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "sonner";
import { Session, getServerSession } from "next-auth";
import { authOptions } from "@/libs/auth";
// import { getTotalItems } from "./(carts)/cart/action";
// import { getTotalWishlist } from "./(carts)/wishlist/action";

import "../styles/globals.css";
import { SubNavbar } from "@/components/common/sub-navbar";

export const metadata: Metadata = {
  title: "Kaki Herbals",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session: Session | null = await getServerSession(authOptions);
  // const totalItemsCart = await getTotalItems(session);
  // const totalItemsWishlists = await getTotalWishlist();

  return (
    <html lang="en">
      
        <body className={GeistSans.className}>
                <SubNavbar address="Address:1536/1/1054 ΜADEHGANJ KHADRA NEAR AWADH EDUCATIONAL ACADEMY INTER COLLEGE SITAPUR ROAD Lucknow UP 226020" />

          <Navbar
            session={session}
            totalItemsCart={2}
            totalWishlists={2}
          />
          <main className="pointer-events-auto bg-white">
            {children}
            <Toaster position="top-right" />
            <Analytics />
            <SpeedInsights />
          </main>
          <Footer />
        </body>
      
    </html>
  );
}
